name: CodePlay

services:
  application:
    container_name: codeplay-app
    image: code-play-image:latest
    env_file: prod-spring.env
    ports:
      - "8080:8080"
    networks:
      - umc_code_play

  database:
    container_name: codeplay-db
    image: mysql:latest
    env_file: prod-db.env
    volumes:
      - /home/ubuntu/deploy-db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - umc_code_play
    command: [ "--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci" ] # MySQL 서버가 실행될 때 사용할 문자셋 및 정렬 규칙 지정

networks:
  umc_code_play:
    driver: bridge # "브리지 네트워크"를 자동 생성하고 컨테이너 간 통신이 가능하도록 설정